use super::*;

impl CEmitter {
    // ── Type mapping ──────────────────────────────────────────

    #[allow(clippy::only_used_in_recursion)]
    pub(super) fn c_type(&self, ty: &Type) -> String {
        match ty {
            Type::I8 => "int8_t".into(),
            Type::I16 => "int16_t".into(),
            Type::I32 => "int32_t".into(),
            Type::I64 => "int64_t".into(),
            Type::U8 => "uint8_t".into(),
            Type::U16 => "uint16_t".into(),
            Type::U32 => "uint32_t".into(),
            Type::U64 => "uint64_t".into(),
            Type::Usize => "size_t".into(),
            Type::F32 => "float".into(),
            Type::F64 => "double".into(),
            Type::Bool => "bool".into(),
            Type::Void => "void".into(),
            Type::Str => "zen_str".into(),
            Type::String => "zen_string".into(),
            Type::Named(name) => c_ident(name),
            Type::Struct { name, .. } => c_ident(name),
            Type::Enum { name, .. } => c_ident(name),
            Type::Array { elem, size } => match size {
                Some(_) => self.c_type(elem), // arrays passed as pointers
                None => self.c_type(elem),
            },
            Type::Slice(elem) => format!("{}*", self.c_type(elem)),
            Type::Ptr(inner) => format!("const {}*", self.c_type(inner)),
            Type::MutPtr(inner) => format!("{}*", self.c_type(inner)),
            Type::RawPtr(inner) => format!("{}*", self.c_type(inner)),
            Type::Function { params, ret } => {
                let ps: Vec<_> = params.iter().map(|p| self.c_type(p)).collect();
                format!("{}(*)({})", self.c_type(ret), ps.join(", "))
            }
            Type::Never => "void".into(),
            Type::Unknown => "void /* unknown */".into(),
        }
    }

    // ── Program ───────────────────────────────────────────────

    pub(super) fn emit_program(&mut self, program: &TypedProgram) {
        // Preamble
        self.line("/* Generated by zen compiler v0.8.0 */");
        self.line("#include <stdint.h>");
        self.line("#include <stdbool.h>");
        self.line("#include <stddef.h>");
        self.line("#include <stdio.h>");
        self.line("#include <stdlib.h>");
        self.line("#include <string.h>");
        self.blank();

        // Runtime types
        self.emit_runtime_types();

        // Forward declarations for all types
        for typedef in &program.types {
            self.line(&format!(
                "typedef struct {} {};",
                c_ident(&typedef.name),
                c_ident(&typedef.name)
            ));
        }
        if !program.types.is_empty() {
            self.blank();
        }

        // Type definitions
        for typedef in &program.types {
            self.emit_type_def(typedef);
            self.blank();
        }

        // Function forward declarations
        for func in &program.functions {
            self.emit_function_forward_decl(func);
        }
        if !program.functions.is_empty() {
            self.blank();
        }

        // Global variables
        for global in &program.globals {
            self.emit_global(global);
        }
        if !program.globals.is_empty() {
            self.blank();
        }

        // I/O helper functions (used by demo)
        self.emit_io_helpers();

        // Function bodies
        for func in &program.functions {
            self.emit_function(func);
            self.blank();
        }

        // Main entry point — Zen's main is renamed to zen_main to avoid
        // conflicting with the C entry point.
        if program.entry_point.is_some() {
            self.line("int main(int argc, char** argv) {");
            self.indent();
            self.line("return zen_main();");
            self.dedent();
            self.line("}");
        }
    }

    fn emit_runtime_types(&mut self) {
        self.line("/* Runtime types */");
        self.line("typedef struct { const char* ptr; size_t len; } zen_str;");
        self.line("typedef struct { char* ptr; size_t len; size_t cap; } zen_string;");
        self.blank();

        // String helpers
        self.line("static zen_str zen_str_from_literal(const char* s) {");
        self.indent();
        self.line("return (zen_str){ .ptr = s, .len = strlen(s) };");
        self.dedent();
        self.line("}");
        self.blank();

        // Printf helper for zen_str
        self.line("static void zen_str_print(zen_str s) {");
        self.indent();
        self.line("fwrite(s.ptr, 1, s.len, stdout);");
        self.dedent();
        self.line("}");
        self.blank();

        // Int to string helper
        self.line("static zen_str zen_i64_to_str(int64_t v, char* buf, size_t bufsz) {");
        self.indent();
        self.line("int n = snprintf(buf, bufsz, \"%lld\", (long long)v);");
        self.line("return (zen_str){ .ptr = buf, .len = (size_t)(n > 0 ? n : 0) };");
        self.dedent();
        self.line("}");
        self.blank();

        // Float to string helper
        self.line("static zen_str zen_f64_to_str(double v, char* buf, size_t bufsz) {");
        self.indent();
        self.line("int n = snprintf(buf, bufsz, \"%g\", v);");
        self.line("return (zen_str){ .ptr = buf, .len = (size_t)(n > 0 ? n : 0) };");
        self.dedent();
        self.line("}");
        self.blank();

        // String concatenation helper (stack-based for now)
        self.line("static zen_str zen_str_concat(zen_str a, zen_str b, char* buf, size_t bufsz) {");
        self.indent();
        self.line("size_t total = a.len + b.len;");
        self.line("if (total > bufsz - 1) total = bufsz - 1;");
        self.line("memcpy(buf, a.ptr, a.len < total ? a.len : total);");
        self.line("if (a.len < total) memcpy(buf + a.len, b.ptr, total - a.len);");
        self.line("buf[total] = '\\0';");
        self.line("return (zen_str){ .ptr = buf, .len = total };");
        self.dedent();
        self.line("}");
        self.blank();
    }

    fn emit_io_helpers(&mut self) {
        self.line("/* I/O helpers (stdlib stand-in) */");
        self.line("static void io_println(zen_str s) {");
        self.indent();
        self.line("fwrite(s.ptr, 1, s.len, stdout);");
        self.line("fputc('\\n', stdout);");
        self.dedent();
        self.line("}");
        self.blank();

        self.line("static void io_print(zen_str s) {");
        self.indent();
        self.line("fwrite(s.ptr, 1, s.len, stdout);");
        self.dedent();
        self.line("}");
        self.blank();
    }

    // ── Type definitions ──────────────────────────────────────

    fn emit_type_def(&mut self, typedef: &TypedTypeDef) {
        let name = c_ident(&typedef.name);
        match &typedef.kind {
            TypeDefKind::Struct { fields } => {
                self.line(&format!("struct {} {{", name));
                self.indent();
                for (field_name, field_type) in fields {
                    self.line(&format!(
                        "{} {};",
                        self.c_type(field_type),
                        c_ident(field_name)
                    ));
                }
                self.dedent();
                self.line("};");
            }
            TypeDefKind::Enum { variants } => {
                // Tagged union
                self.line(&format!("enum {}_Tag {{", name));
                self.indent();
                for variant in variants {
                    self.line(&format!(
                        "{}_{} = {},",
                        name,
                        c_ident(&variant.name),
                        variant.tag
                    ));
                }
                self.dedent();
                self.line("};");
                self.blank();

                self.line(&format!("struct {} {{", name));
                self.indent();
                self.line(&format!("enum {}_Tag tag;", name));

                // Only emit union if any variant has a payload
                let has_payloads = variants.iter().any(|v| v.payload.is_some());
                if has_payloads {
                    self.line("union {");
                    self.indent();
                    for variant in variants {
                        if let Some(fields) = &variant.payload {
                            if fields.len() == 1 {
                                self.line(&format!(
                                    "{} {};",
                                    self.c_type(&fields[0].1),
                                    c_ident(&variant.name).to_lowercase()
                                ));
                            } else {
                                self.line("struct {");
                                self.indent();
                                for (fname, ftype) in fields {
                                    self.line(&format!(
                                        "{} {};",
                                        self.c_type(ftype),
                                        c_ident(fname)
                                    ));
                                }
                                self.dedent();
                                self.line(&format!(
                                    "}} {};",
                                    c_ident(&variant.name).to_lowercase()
                                ));
                            }
                        }
                    }
                    self.dedent();
                    self.line("} data;");
                }
                self.dedent();
                self.line("};");
            }
        }

        // Methods
        for method in &typedef.methods {
            self.blank();
            self.emit_function(method);
        }
    }

    // ── Functions ─────────────────────────────────────────────

    fn emit_function_forward_decl(&mut self, func: &TypedFunction) {
        let ret = self.c_type(&func.return_type);
        let name = c_func_ident(&func.name);
        let params = self.format_params(&func.params);
        self.line(&format!("{} {}({});", ret, name, params));
    }

    pub(super) fn emit_function(&mut self, func: &TypedFunction) {
        let ret = self.c_type(&func.return_type);
        let name = c_func_ident(&func.name);
        let params = self.format_params(&func.params);
        self.line(&format!("{} {}({}) {{", ret, name, params));
        self.indent();

        // Emit statements
        for stmt in &func.body.statements {
            self.emit_statement(stmt);
        }

        // Emit trailing expression — for non-void functions, ensure the result
        // is returned (especially important for match expressions).
        if let Some(ref expr) = func.body.expr {
            if func.return_type != Type::Void && func.return_type != Type::Never {
                match &expr.kind {
                    TypedExprKind::Return(_) => {
                        let s = self.emit_expr_to_stmt(expr);
                        if !s.is_empty() {
                            self.line(&s);
                        }
                    }
                    TypedExprKind::Match {
                        scrutinee,
                        arms,
                        kind,
                    } => {
                        let tmp = self.fresh_tmp();
                        let ty = self.c_type(&func.return_type);
                        self.line(&format!("{} {};", ty, tmp));
                        self.emit_match(scrutinee, arms, kind, Some(&tmp));
                        self.line(&format!("return {};", tmp));
                    }
                    _ => {
                        let val = self.emit_expr_inline(expr);
                        if !val.is_empty() {
                            self.line(&format!("return {};", val));
                        }
                    }
                }
            } else {
                let s = self.emit_expr_to_stmt(expr);
                if !s.is_empty() {
                    self.line(&s);
                }
            }
        }

        self.dedent();
        self.line("}");
    }

    fn format_params(&self, params: &[TypedParam]) -> String {
        if params.is_empty() {
            return "void".into();
        }
        params
            .iter()
            .map(|p| format!("{} {}", self.c_type(&p.ty), c_ident(&p.name)))
            .collect::<Vec<_>>()
            .join(", ")
    }

    // ── Globals ───────────────────────────────────────────────

    fn emit_global(&mut self, global: &TypedGlobal) {
        let ty = self.c_type(&global.ty);
        let name = c_ident(&global.name);
        let val = self.emit_expr_inline(&global.value);
        if global.mutable {
            self.line(&format!("{} {} = {};", ty, name, val));
        } else {
            self.line(&format!("const {} {} = {};", ty, name, val));
        }
    }
}
