use super::*;

mod runtime_helpers;

impl CEmitter {
    pub(super) fn c_type(ty: &Type) -> String {
        match ty {
            Type::I8 => "int8_t".into(),
            Type::I16 => "int16_t".into(),
            Type::I32 => "int32_t".into(),
            Type::I64 => "int64_t".into(),
            Type::U8 => "uint8_t".into(),
            Type::U16 => "uint16_t".into(),
            Type::U32 => "uint32_t".into(),
            Type::U64 => "uint64_t".into(),
            Type::Usize => "size_t".into(),
            Type::F32 => "float".into(),
            Type::F64 => "double".into(),
            Type::Bool => "bool".into(),
            Type::Void | Type::Never => "void".into(),
            Type::Str => "zen_str".into(),
            Type::Named(name) | Type::Struct { name, .. } | Type::Enum { name, .. } => {
                c_ident(name)
            }
            Type::Array { elem, .. } => Self::c_type(elem),
            Type::Slice(elem) => format!("{}*", Self::c_type(elem)),
            Type::Ptr(inner) => format!("const {}*", Self::c_type(inner)),
            Type::MutPtr(inner) | Type::RawPtr(inner) => format!("{}*", Self::c_type(inner)),
            Type::Function { params, ret } => {
                let ps: Vec<_> = params.iter().map(Self::c_type).collect();
                format!("{}(*)({})", Self::c_type(ret), ps.join(", "))
            }
            Type::Unknown => "void /* unknown */".into(),
        }
    }

    pub(super) fn emit_program(&mut self, program: &TypedProgram) {
        self.line("/* Generated by zen compiler v0.8.0 */");
        self.line("#include <stdint.h>");
        self.line("#include <stdbool.h>");
        self.line("#include <stddef.h>");
        self.line("#include <stdio.h>");
        self.line("#include <stdlib.h>");
        self.line("#include <string.h>");
        self.line("#include <unistd.h>");
        self.blank();

        self.emit_runtime_types();

        for typedef in &program.types {
            let name = c_ident(&typedef.name);
            self.line(&format!("typedef struct {name} {name};"));
        }
        if !program.types.is_empty() {
            self.blank();
        }

        for typedef in &program.types {
            self.emit_type_def(typedef);
            self.blank();
        }

        for func in &program.functions {
            let ret = Self::c_type(&func.return_type);
            let name = c_func_ident(&func.name);
            let params = self.format_params(&func.params);
            self.line(&format!("{} {}({});", ret, name, params));
        }
        if !program.functions.is_empty() {
            self.blank();
        }

        for global in &program.globals {
            let ty = Self::c_type(&global.ty);
            let name = c_ident(&global.name);
            let val = self.emit_expr_inline(&global.value);
            let qualifier = c_const_qualifier(global.mutable);
            self.line(&format!("{qualifier}{ty} {name} = {val};"));
        }
        if !program.globals.is_empty() {
            self.blank();
        }

        for func in &program.functions {
            self.emit_function(func);
            self.blank();
        }

        if program.entry_point.is_some() {
            self.line("int main(int argc, char** argv) {");
            self.indent();
            self.line("return zen_main();");
            self.dedent();
            self.line("}");
        }
    }

    fn emit_type_def(&mut self, typedef: &TypedTypeDef) {
        let name = c_ident(&typedef.name);
        match &typedef.kind {
            TypeDefKind::Struct { fields } => {
                self.line(&format!("struct {} {{", name));
                self.indent();
                for (field_name, field_type) in fields {
                    self.line(&format!(
                        "{} {};",
                        Self::c_type(field_type),
                        c_ident(field_name)
                    ));
                }
                self.dedent();
                self.line("};");
            }
            TypeDefKind::Enum { variants } => {
                self.line(&format!("enum {}_Tag {{", name));
                self.indent();
                for variant in variants {
                    self.line(&format!(
                        "{}_{} = {},",
                        name,
                        c_ident(&variant.name),
                        variant.tag
                    ));
                }
                self.dedent();
                self.line("};");
                self.blank();

                self.line(&format!("struct {} {{", name));
                self.indent();
                self.line(&format!("enum {}_Tag tag;", name));

                if variants.iter().any(|v| v.payload.is_some()) {
                    self.line("union {");
                    self.indent();
                    for variant in variants {
                        if let Some(payload) = &variant.payload {
                            self.line(&format!(
                                "{} {};",
                                Self::c_type(payload),
                                c_ident(&variant.name).to_lowercase()
                            ));
                        }
                    }
                    self.dedent();
                    self.line("} data;");
                }
                self.dedent();
                self.line("};");
            }
        }
    }
}
