use super::*;

mod runtime_helpers;
mod type_defs;

impl CEmitter {
    // ── Type mapping ──────────────────────────────────────────

    #[allow(clippy::only_used_in_recursion)]
    pub(super) fn c_type(&self, ty: &Type) -> String {
        match ty {
            Type::I8 => "int8_t".into(),
            Type::I16 => "int16_t".into(),
            Type::I32 => "int32_t".into(),
            Type::I64 => "int64_t".into(),
            Type::U8 => "uint8_t".into(),
            Type::U16 => "uint16_t".into(),
            Type::U32 => "uint32_t".into(),
            Type::U64 => "uint64_t".into(),
            Type::Usize => "size_t".into(),
            Type::F32 => "float".into(),
            Type::F64 => "double".into(),
            Type::Bool => "bool".into(),
            Type::Void => "void".into(),
            Type::Str => "zen_str".into(),
            Type::String => "zen_string".into(),
            Type::Named(name) => c_ident(name),
            Type::Struct { name, .. } => c_ident(name),
            Type::Enum { name, .. } => c_ident(name),
            Type::Array { elem, size } => match size {
                Some(_) => self.c_type(elem), // arrays passed as pointers
                None => self.c_type(elem),
            },
            Type::Slice(elem) => format!("{}*", self.c_type(elem)),
            Type::Ptr(inner) => format!("const {}*", self.c_type(inner)),
            Type::MutPtr(inner) => format!("{}*", self.c_type(inner)),
            Type::RawPtr(inner) => format!("{}*", self.c_type(inner)),
            Type::Function { params, ret } => {
                let ps: Vec<_> = params.iter().map(|p| self.c_type(p)).collect();
                format!("{}(*)({})", self.c_type(ret), ps.join(", "))
            }
            Type::Never => "void".into(),
            Type::Unknown => "void /* unknown */".into(),
        }
    }

    // ── Program ───────────────────────────────────────────────

    pub(super) fn emit_program(&mut self, program: &TypedProgram) {
        // Preamble
        self.line("/* Generated by zen compiler v0.8.0 */");
        self.line("#include <stdint.h>");
        self.line("#include <stdbool.h>");
        self.line("#include <stddef.h>");
        self.line("#include <stdio.h>");
        self.line("#include <stdlib.h>");
        self.line("#include <string.h>");
        self.line("#include <unistd.h>");
        self.line("#include <sys/syscall.h>");
        self.blank();

        // Runtime types
        self.emit_runtime_types();

        // Forward declarations for all types
        for typedef in &program.types {
            self.line(&format!(
                "typedef struct {} {};",
                c_ident(&typedef.name),
                c_ident(&typedef.name)
            ));
        }
        if !program.types.is_empty() {
            self.blank();
        }

        // Type definitions
        for typedef in &program.types {
            self.emit_type_def(typedef);
            self.blank();
        }

        // Function forward declarations
        for func in &program.functions {
            self.emit_function_forward_decl(func);
        }
        if !program.functions.is_empty() {
            self.blank();
        }

        // Global variables
        for global in &program.globals {
            self.emit_global(global);
        }
        if !program.globals.is_empty() {
            self.blank();
        }

        // I/O helper functions (used by demo)
        self.emit_io_helpers();

        // Scan all functions for closures and collect their definitions
        self.collect_closure_defs(program);
        // Emit closure env structs and functions
        if !self.closure_defs.is_empty() {
            self.line("/* Closure definitions */");
            let defs = std::mem::take(&mut self.closure_defs);
            for def in &defs {
                self.output.push_str(def);
                self.blank();
            }
        }

        // Function bodies
        for func in &program.functions {
            self.emit_function(func);
            self.blank();
        }

        // Main entry point — Zen's main is renamed to zen_main to avoid
        // conflicting with the C entry point.
        if program.entry_point.is_some() {
            self.line("int main(int argc, char** argv) {");
            self.indent();
            self.line("return zen_main();");
            self.dedent();
            self.line("}");
        }
    }
}
